export const DATA = 
[
    {
        key: 0,
        abxTaskId: -1,
        organisationTaskId:-1,
        organisationId: -1,
        timestamp: null,
        assignedTo: "",
        taskSummary: "task 1",
        taskDescription: "desc 1",
        taskStatus: "Not Started",
        priority: "LOW"
    },
    {
        key: 1,
        abxTaskId: -1,
        organisationTaskId:-1,
        organisationId: -1,
        timestamp: null,
        assignedTo: "",
        taskSummary: "task 2",
        taskDescription: "desc 2",
        taskStatus: "In Progress",
        priority: "LOW"
    },
    {
        key: 2,
        abxTaskId: -1,
        organisationTaskId:-1,
        organisationId: -1,
        timestamp: null,
        assignedTo: "",
        taskSummary: "task 3",
        taskDescription: "desc 3",
        taskStatus: "Not Started",
        priority: "LOW"
    },
    {
        key: 3,
        abxTaskId: -1,
        organisationTaskId:-1,
        organisationId: -1,
        timestamp: null,
        assignedTo: "",
        taskSummary: "task 4",
        taskDescription: "desc 4",
        taskStatus: "Completed",
        priority: "HIGH"
    },
    {
        key: 4,
        abxTaskId: -1,
        organisationTaskId:-1,
        organisationId: -1,
        timestamp: null,
        assignedTo: "",
        taskSummary: "task 5",
        taskDescription: "desc 5",
        taskStatus: "Not Started",
        priority: "LOW"
    },
    {
        key: 5,
        abxTaskId: -1,
        organisationTaskId:-1,
        organisationId: -1,
        timestamp: null,
        assignedTo: "",
        taskSummary: "task 6",
        taskDescription: "desc 6",
        taskStatus: "Not Started",
        priority: "LOW"
    },
    {
        key: 6,
        abxTaskId: -1,
        organisationTaskId:-1,
        organisationId: -1,
        timestamp: null,
        assignedTo: "",
        taskSummary: "task 7",
        taskDescription: "desc 7",
        taskStatus: "Not Started",
        priority: "LOW"
    },
    {
        key: 7,
        abxTaskId: -1,
        organisationTaskId:-1,
        organisationId: -1,
        timestamp: null,
        assignedTo: "",
        taskSummary: "task 8",
        taskDescription: "desc 8",
        taskStatus: "Not Started",
        priority: "LOW"
    },
    {
        key: 8,
        abxTaskId: -1,
        organisationTaskId:-1,
        organisationId: -1,
        timestamp: null,
        assignedTo: "",
        taskSummary: "task 9",
        taskDescription: "desc 9",
        taskStatus: "Not Started",
        priority: "LOW"
    },
    {
        key: 9,
        abxTaskId: -1,
        organisationTaskId:-1,
        organisationId: -1,
        timestamp: null,
        assignedTo: "",
        taskSummary: "task 10",
        taskDescription: "desc 10",
        taskStatus: "Not Started",
        priority: "LOW"
    },
    {
        key: 10,
        abxTaskId: -1,
        organisationTaskId:-1,
        organisationId: -1,
        timestamp: null,
        assignedTo: "",
        taskSummary: "task 11",
        taskDescription: "desc 11",
        taskStatus: "Not Started",
        priority: "LOW"
    },
    {
        key: 11,
        abxTaskId: -1,
        organisationTaskId:-1,
        organisationId: -1,
        timestamp: null,
        assignedTo: "",
        taskSummary: "task 12",
        taskDescription: "desc 12",
        taskStatus: "Not Started",
        priority: "LOW"
    },
    {
        key: 12,
        abxTaskId: -1,
        organisationTaskId:-1,
        organisationId: -1,
        timestamp: null,
        assignedTo: "",
        taskSummary: "task 13",
        taskDescription: "desc 13",
        taskStatus: "Not Started",
        priority: "LOW"
    },
    {
        key: 13,
        abxTaskId: -1,
        organisationTaskId:-1,
        organisationId: -1,
        timestamp: null,
        assignedTo: "",
        taskSummary: "task 14",
        taskDescription: "desc 14",
        taskStatus: "Not Started",
        priority: "LOW"
    },
    {
        key: 14,
        abxTaskId: -1,
        organisationTaskId:-1,
        organisationId: -1,
        timestamp: null,
        assignedTo: "",
        taskSummary: "task 15",
        taskDescription: "desc 15",
        taskStatus: "Not Started",
        priority: "LOW"
    }
]